# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            DKade
tagline:          'A Jekyll theme'
description:      'Dietrich Schwartz<br>♡<br>Katia Feltroof'
baseurl: "/dekade-archive"
url: https://mistynocturn-design.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

# Archive chat logs
collections:
  twitter:
    output: true
    permalink: /twitter/:name/
  archive:
    output: true
    permalink: /archive/:name/

