(function(){
  'use strict';
  var BASE='/dekade-archive/',rootHandle=null,folderHandle=null,parts=[],nextSheetNumber=1;
  function $(id){return document.getElementById(id)}
  function show(text,ready){$('assetStatus').innerHTML=text;$('assetStatus').style.color=ready?'#4f765c':'#8a6464'}
  function paths(){return $('pdfs').value.split(/\r?\n/).map(function(x){return x.trim()}).filter(Boolean)}
  function appendPath(path){var values=paths();if(values.indexOf(path)<0)values.push(path);$('pdfs').value=values.join('\n');$('pdfs').dispatchEvent(new Event('input',{bubbles:true}))}
  async function scanNextSheetNumber(){var max=0;for await(var entry of folderHandle.values()){if(entry.kind!=='file')continue;if(/^sheet\.pdf$/i.test(entry.name)){max=Math.max(max,1);continue}var match=entry.name.match(/^sheet(\d+)\.pdf$/i);if(match)max=Math.max(max,Number(match[1]))}nextSheetNumber=max+1}
  async function connect(){if(folderHandle)return true;if(!window.showDirectoryPicker){show('폴더 연결은 Chrome 또는 Edge에서 사용할 수 있습니다.',false);return false}try{show('먼저 <strong>dekade-archive</strong> 저장소 폴더를 선택하세요.',false);rootHandle=await window.showDirectoryPicker({id:'dekade-checklist-root',mode:'readwrite'});window.alert('이제 assets/checklists 안의 이 체크리스트 전용 폴더를 선택하세요. 새 폴더를 만들어도 됩니다.');folderHandle=await window.showDirectoryPicker({id:'dekade-checklist-assets',mode:'readwrite',startIn:rootHandle});parts=await rootHandle.resolve(folderHandle);if(!parts||parts.length<3||parts[0].toLowerCase()!=='assets'||parts[1].toLowerCase()!=='checklists'){folderHandle=null;parts=[];throw Error('assets/checklists 안의 목록별 폴더를 선택하세요.')}await scanNextSheetNumber();show('연결 완료: <code>'+parts.join('/')+'/</code> · 다음 PDF는 <strong>sheet'+nextSheetNumber+'.pdf</strong>로 저장됩니다.',true);return true}catch(error){if(error.name!=='AbortError')show(error.message,false);return false}}
  async function savePdf(file){var targetName='sheet'+nextSheetNumber+'.pdf',path=BASE+parts.join('/')+'/'+targetName;show('<strong>'+targetName+'</strong> 저장 중…',true);try{var handle=await folderHandle.getFileHandle(targetName,{create:true}),writable=await handle.createWritable();await writable.write(file);await writable.close();appendPath(path);nextSheetNumber+=1;show('<strong>'+targetName+'</strong> 저장 완료 · '+paths().length+'개의 PDF가 등록되었습니다. 다음 파일은 <strong>sheet'+nextSheetNumber+'.pdf</strong>입니다.',true);return true}catch(error){show('PDF 저장에 실패했습니다: '+error.message,false);return false}}
  var style=document.createElement('style');style.textContent='.asset-pick{display:inline-flex;margin-top:4px}.asset-pick input{height:1px;opacity:0;position:absolute;width:1px}.asset-pick button{background:#fff;border:1px solid #cbc6ca;border-radius:4px;color:#6c646b;cursor:pointer;font-size:.59rem;font-weight:750;padding:6px 8px}';document.head.appendChild(style);
  var wrap=document.createElement('span');wrap.className='asset-pick';wrap.innerHTML='<input id="checklistPdfFile" type="file" accept="application/pdf" multiple><button type="button">PDF 파일 추가</button>';var input=wrap.querySelector('input'),button=wrap.querySelector('button');$('pdfs').insertAdjacentElement('afterend',wrap);
  button.onclick=function(){if(!folderHandle){show('먼저 PDF 저장 폴더 연결을 완료하세요.',false);return}input.click()};
  input.onchange=async function(){var files=Array.prototype.slice.call(this.files);this.value='';for(var i=0;i<files.length;i+=1)await savePdf(files[i])};
  $('connectAssets').onclick=connect;
})();
